### ISSUE TITLE
check_datastax_opscenter_cassandra_replication.pl - invalid keyspace defined: must be alphanumeric

### ISSUE THREAD

**Issue by joelsdc** [HariSekhon/nagios-plugins#101]
Hi, 

I'm not sure if i'm doing some wrong, maybe its a bug. I'm suing the cassandra replication plugin and I get the following error:

1- List the keyspaces:

```
root@nagios:/usr/local/nagios/libexec/harisekhon# ./check_datastax_opscenter_cassandra_replication.pl -H opscenter1.local --password "no-password" -C Default --list-keyspaces
Keyspaces in cluster 'Default':

OpsCenter
healthcheck
system
system_traces
user
voice_history
root@nagios:/usr/local/nagios/libexec/harisekhon#
```

2- Specify a keyspace:

```
root@nagios:/usr/local/nagios/libexec/harisekhon# ./check_datastax_opscenter_cassandra_replication.pl -H opscenter1.local --password "no-password" -C Default -K voice_history
invalid keyspace defined: must be alphanumeric

usage: check_datastax_opscenter_cassandra_replication.pl [ options ]

-H  --host                    DataStax OpsCenter host ($DATASTAX_OPSCENTER_HOST, $HOST)
-P  --port                    DataStax OpsCenter port ($DATASTAX_OPSCENTER_PORT, $PORT, default: 8888)
-u  --user                    DataStax OpsCenter user ($DATASTAX_OPSCENTER_USERNAME, $DATASTAX_OPSCENTER_USER, $USERNAME, $USER)
-p  --password                DataStax OpsCenter password ($DATASTAX_OPSCENTER_PASSWORD, $PASSWORD)
-C  --cluster                 Cluster as named in DataStax OpsCenter ($DATASTAX_OPSCENTER_CLUSTER, $CLUSTER). See --list-clusters
-K  --keyspace                KeySpace to check ($DATASTAX_OPSCENTER_KEYSPACE, $KEYSPACE). See --list-keyspaces
-F  --replication-factor      Replication factor to expect (integer, optional)
-S  --replication-strategy    Replication strategy to expect (string of class name eg. 'org.apache.cassandra.locator.SimpleStrategy', optional)
-W  --no-durable-writes       Expect non-durable writes (default is to expect durable writes)
    --list-clusters           List clusters managed by DataStax OpsCenter
    --list-keyspaces          List keyspaces in given Cassandra cluster managed by DataStax OpsCenter. Requires --cluster
-t  --timeout                 Timeout in secs (default: 10)
-v  --verbose                 Verbose mode (-v, -vv, -vvv ...)
-h  --help                    Print description and usage options
-V  --version                 Print version and exit
root@nagios:/usr/local/nagios/libexec/harisekhon#
```

So I'm listing the keyspaces correctly, but when I specify one that has an "underscore" it fails.

Is this expected?

Thanks!

**Comment by HariSekhon** [comment]
@joelsdc 

Thanks for reporting this.

The validation was overly strict, I've just pushed an update that should help, please try again and let me know.

Thanks

Hari

**Comment by joelsdc** [comment]
Hi Hari, 

I have done 'git pull' & 'make'.

Now the result is a little different, but still fails:

```
root@nagios:/usr/local/nagios/libexec/harisekhon# ./check_datastax_opscenter_cassandra_replication.pl -H opscenter1.local --password "no-password" -C Default -K voice_history
invalid \w defined: must be one of the following chars - keyspace

usage: check_datastax_opscenter_cassandra_replication.pl [ options ]

```

**Comment by HariSekhon** [comment]
Try ```make update-no-recompile``` for a quick update and then retry, it should work now..

**Comment by joelsdc** [comment]
Hi, I can confirm I'm not getting the error anymore.

Thanks!
