### ISSUE TITLE
check_mysql_query.pl: Unable to get Terminal Size.

### ISSUE THREAD

**Issue by joelsdc** [HariSekhon/nagios-plugins#113]
Hi, 

I have setup a regular Nagios check running the MySQL query plugin.

The command si this:

`$USER1$/harisekhon/check_mysql_query.pl -H $HOSTADDRESS$ -u $ARG1$ -p $ARG2$ -d $ARG3$ -w $ARG5$ -c $ARG6$ -g -q '$ARG4$'`

If I run it through the shell, it works as expected (both as root or nagios user).

When I run it through Nagios, I get the following output:

_Unable to get Terminal Size. The TIOCGWINSZ ioctl didn't work. The COLUMNS and LINES environment variables didn't work. The resize program didn't work. The stty program didn't work. at /usr/local/lib/perl/5.18.2/Term/ReadKey.pm line 451._ 

I have tried running it with prepending "sudo -u root" to the command to run it as root but the I get the same output.

Any idea what I'm doing wrong?

Thanks!
Joel.

**Comment by HariSekhon** [comment]
It tries to get the terminal size for best --help layout but in your environment it seems all the unusual things aren't available so the underlying Term::ReadKey library is erroring out.

I've just pushed an update to try to make it non-fatal. Please run

```make update-no-recompile```

and try again.

Thanks

Hari

**Comment by joelsdc** [comment]
Hi Hari, 

I did the update-no-recompile. The output is attached.

[update-no-recompile.txt](https://github.com/HariSekhon/nagios-plugins/files/420807/update-no-recompile.txt)

Am I still doing something wrong? Is there an environment setting or something I can do avoid it?

Thanks again!
Joel.

**Comment by joelsdc** [comment]
Just to clarify my previous msg, I am still having the same issue.

**Comment by HariSekhon** [comment]
I'll try to look in to this tonight.

**Comment by HariSekhon** [comment]
@joelsdc 

Is this the complete output or does it output something afterwards like the expected result output? 

Also are you appending some output redirection to the end of the command?

While reproducing this I've found it only seems to occur when I add output redirection like ``` | tee /dev/null``` or ``` > /tmp/tmp``` and also delete the ```stty``` program from the system and nullify the ```$LINES``` and ```$COLUMNS``` implicit environment variables that the shell automatically gives you. FYI there is a pre-built docker image with all the libraries pre-installed that you can use to reproduce this (```harisekhon/nagios-plugins```, available on [DockerHub](https://hub.docker.com/r/harisekhon/nagios-plugins/) (I've just added a shortcut of ```make docker``` to run it if you have docker installed).

So it seems that the reason other people haven't been running in to this is due to the multiple things that have to be wrong with the environment for this to occur and even after I made sure it was a non-fatal error it seems the underlying library will still print the error message, so I've added suppression of the the warning error message.

Depending on the answer to the first question, if it's merely superficial and there is the correct additional output then this should solve it.

Please update again and try again via ```make update-no-recompile``` and re-running your command and pasting the full output.

**Comment by joelsdc** [comment]
Hi Hari, 

To answer your questions:
1- What I attached was the output of the update-no-recompile command (in case you needed it).
2- I run the command without any output redirection (both though console / through Nagios).

I have run the update-no-recompile and now I can run the command from Nagios without getting any errors (and I get the expected output with perfdata).

Thank you again for fixing this.

Best regards, 
Joel.

**Comment by HariSekhon** [comment]
Thanks for confirming.
