### ISSUE TITLE
problems with check_whois and internetbs.net

### ISSUE THREAD

**Issue by juniorfga** [HariSekhon/nagios-plugins#134]
Hello
When I use check_whois for domains on internetbs.net I obtain messages like this:

WARNING: invalid status 'clientTransferProhibited -' found! 322 days left for barcodepack.com domain, expires '23-12-2017' (w=60/c=30) nameservers:ns-canada.topdns.com,ns-uk.topdns.com,ns-usa.topdns.com registrant:'Whois Privacy Corp' registrar:'Internet Domain Service BS Corp' created:2016-12-23 updated:2017-02-03 admin_email:'barcodepack.com-admin-lqno@customers.whoisprivacycorp.com' tech_email:'barcodepack.com-tech-ic2q@customers.whoisprivacycorp.com'

another message

WARNING: invalid status 'ok -' found! 346 days left for titangelchile.com domain, expires '17-01-2018' (w=60/c=30) nameservers:ns1.onlydomains.com,ns2.onlydomains.com,ns3.onlydomains.com registrant:'Registrant of titangelchile.com' registrar:'Instra Corporation Pty' created:2017-01-17 updated:2017-02-04 admin_email:'8787621@privateranger.com' tech_email:'8787621@privateranger.com'

And according to the code it should return an "ok" not a "warning", could you check, please

Regards

**Comment by HariSekhon** [comment]
I've just pushed a fix that should resolve this for you.

**Comment by HariSekhon** [comment]
I'll close this ticket for now as it should be resolved, you can re-open if the issue persists for you.

**Comment by juniorfga** [comment]
Sorry for the delay HariSekhon, the issue is not solved
The solution I've found was to add three lines to the check_plugin.pl code, this is how I have it right now

                        Publicado
                        registered
                        RENEWPERIOD
                        serverDeleteProhibited
                        serverTransferProhibited
                        serverUpdateProhibited
                        TRANSFERPERIOD
                        VERIFIED
                        VerifiedID
                        /;
# add valid statuses with spaces in them
push(@valid_statuses,
    (
        "200 Active",
        "auto-renew grace",
        "CLIENT DELETE PROHIBITED",
        "CLIENT RENEW PROHIBITED",
        "CLIENT TRANSFER PROHIBITED",
        "CLIENT UPDATE PROHIBITED",
        "DELETE PROHIBITED",
        "NOT AVAILABLE",
        "NOT DELEGATED",
        "paid and in zone",
        "Registered until expiry date",
        "SERVER UPDATE PROHIBITED",
        "Transfer Allowed",
        "Transfer Locked",
        "TRANSFER PROHIBITED",
        "clientTransferProhibited -",
        "ok -",
        "UPDATE PROHIBITED"
    )
);
I add the line that says "Publicado" because is a state for ".com.br" domains and two lines "clientTransferProhibited -" and "ok -" to solve the issue with internetbs.net, please if you where so kind of checking it to see if it could be the solution I'll preciated. in order to fix this for the future.
I've attached the file so you can compare
Keep the great work, thanks.

Regards
[check_whois.zip](https://github.com/HariSekhon/nagios-plugins/files/868345/check_whois.zip)

**Comment by HariSekhon** [comment]
Did you `git pull` to try the latest version?

```
./check_whois.pl -V
check_whois.pl version 0.11.2  =>  Hari Sekhon Utils version 1.18.6
...

./check_whois.pl -d barcodepack.com -v
OK: 273 days left for barcodepack.com domain, expires '23-12-2017' (w=60/c=30) nameservers:ns-canada.topdns.com,ns-uk.topdns.com,ns-usa.topdns.com registrant:'Whois Privacy Corp' registrar:'Internet Domain Service BS Corp' created:2016-12-23 updated:2017-03-24 admin_email:'barcodepack.com-admin-lqno@customers.whoisprivacycorp.com' tech_email:'barcodepack.com-tech-ic2q@customers.whoisprivacycorp.com' | whois_query_time=0.4223s
```

**Comment by juniorfga** [comment]
My mistake, no I only did a make, you are right i've made the git pull then make and everything is working fine now.
Could you please add the "Publicado" status for the .com.br domains?
Thanks

**Comment by HariSekhon** [comment]
I've added Publicado to valid statuses, and as this is now working for you domain, I'll go ahead and close this ticket.

Thanks

Hari
