### ISSUE TITLE
check_yum.pl - Use of implicit split to @_ is deprecated

### ISSUE THREAD

**Issue by darknicht66** [HariSekhon/nagios-plugins#190]
Receive the following warning from perl when executing check_yum.pl...

[root@nagios1 nagios-plugins]# ./check_yum.pl --warn-on-any-update --timeout=120 -vvvv
**Use of implicit split to @_ is deprecated at /usr/lib/nagios/plugins/check_yum.pl line 197.**
verbose mode on

check_yum.pl version 0.6.0  =>  Hari Sekhon Utils version 1.18.13

setting timeout to 120 secs

cmd: /usr/bin/yum  --security check-update
output:

Loaded plugins: fastestmirror, priorities, security
Loading mirror speeds from cached hostfile
 * base: mirror.its.dal.ca
 * epel: epel.mirror.constant.com
 * extras: centos.mirror.colo-serv.net
 * updates: centos.mirror.colo-serv.net
266 packages excluded due to repository priority protections
Limiting package lists to security relevant ones
No packages needed for security; 9 packages available

exitcode: 0

WARNING: 0 Yum Security Updates Available, 9 Non-Security Updates Available | security_updates_available=0 non_security_updates_available=9 yum_updates_available=9

[root@nagios1 nagios-plugins]# perl --version

This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

Copyright 1987-2009, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by HariSekhon** [comment]
Please try the latest version I've just pushed, which should get rid of this superficial warning.

Thanks

Hari

**Comment by darknicht66** [comment]
Still the same issue, but the following change appears to work for me...

diff check_yum.pl ../check_yum.pl
202c202
<             if(scalar (() = split(/\s+/, $line)) > 1 and $line !~ /^\s/o and $line !~ /Obsoleting Packages/o){
---
>             if(scalar split(/\s+/, $line) > 1 and $line !~ /^\s/o and $line !~ /Obsoleting Packages/o){

**Comment by HariSekhon** [comment]
It's odd I don't get this warning, but I've modified the line that seems to be giving you this warning to be a little bit less syntactically magical.

Please try the latest version to see if this gets rid of the warning message and let me know.

Thanks

Hari

**Comment by darknicht66** [comment]
Perfect! You are correct, that works and it's much easier to read and understand what's happening than the syntax 'magic' I gave you. Mark this as 'case closed.' Thanks!
