### ISSUE TITLE
Use of uninitialized value in undef operator at lib/HariSekhonUtils.pm line 562

### ISSUE THREAD

**Issue by chaitu011** [HariSekhon/nagios-plugins#88]
I'm running check_hadoop_jmx.pl plugin and getting following error - 

./check_hadoop_jmx.pl -H 10.213.162.54 -P 60030 --bean Hadoop:service=HBase,name=JvmMetrics -a
Use of uninitialized value in undef operator at lib/HariSekhonUtils.pm line 562.
OK: Hadoop:service=HBase,name=JvmMetrics: GcCount=31320, GcCountConcurrentMarkSweep=5, GcCountParNew=31315, GcTimeMillis=85572, GcTimeMillisConcurrentMarkSweep=48, GcTimeMillisParNew=85524, LogError=0, LogFatal=0, LogInfo=0, LogWarn=0, MemHeapCommittedM=122.375, MemHeapMaxM=1956.4375, MemHeapUsedM=21.330322, MemMaxM=1956.4375, MemNonHeapCommittedM=54.73828, MemNonHeapMaxM=130, MemNonHeapUsedM=34.035538, ThreadsBlocked=0, ThreadsNew=0, ThreadsRunnable=20, ThreadsTerminated=0, ThreadsTimedWaiting=16, ThreadsWaiting=80, modelerType=JvmMetrics, tag.Context=jvm, tag.Hostname=ban-inf-d-mapr1, tag.ProcessName=IPC, tag.SessionId=| 'GcCount'=31320 'GcCountConcurrentMarkSweep'=5 'GcCountParNew'=31315 'GcTimeMillis'=85572 'GcTimeMillisConcurrentMarkSweep'=48 'GcTimeMillisParNew'=85524 'LogError'=0 'LogFatal'=0 'LogInfo'=0 'LogWarn'=0 'MemHeapCommittedM'=122.375 'MemHeapMaxM'=1956.4375 'MemHeapUsedM'=21.330322 'MemMaxM'=1956.4375 'MemNonHeapCommittedM'=54.73828 'MemNonHeapMaxM'=130 'MemNonHeapUsedM'=34.035538 'ThreadsBlocked'=0 'ThreadsNew'=0 'ThreadsRunnable'=20 'ThreadsTerminated'=0 'ThreadsTimedWaiting'=16 'ThreadsWaiting'=80
-------------------------------------------------------------------------------------------
./check_hadoop_jmx.pl -H 10.213.162.54 -P 60030 --bean Hadoop:service=HBase,name=RegionServer,sub=Server -m compactionQueueLength
Use of uninitialized value in undef operator at lib/HariSekhonUtils.pm line 562.
OK: Hadoop:service=HBase,name=RegionServer,sub=Server: compactionQueueLength=0 | 'compactionQueueLength'=0;;;
----------------------------------------------------------------------------------

I've freshly downloaded and installed Nagios plugins as per your installation process. Any idea if I'm missing anything..?

Thanks in Advance
-- Anil Kumar V

**Comment by HariSekhon** [comment]
Hi Anil,

Thanks for raising this, it's a minor non-functional warning, I've pushed a patch to avoid it. The status and behaviour of the plugin is correct regardless in terms of the status code OK, service output and perfdata for graphing.

To get the latest update, please run
```
make update-no-recompile
```
and then try again and that warning shouldn't appear any more.

Thanks

Hari

**Comment by chaitu011** [comment]
Thanks for the response. I've updated and re-run the check. Seems to be getting into same issue. The status output of the plugin is returns fine, but getting additional warning message.

# make update-no-recompile
git pull
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/harisekhon/nagios-plugins
   6c6ed5d..b88713c  master     -> origin/master
Fetching submodule lib
remote: Counting objects: 3, done.
remote: Total 3 (delta 2), reused 2 (delta 2), pack-reused 1
Unpacking objects: 100% (3/3), done.
From https://github.com/harisekhon/lib
   6fb8eac..452b8de  master     -> origin/master
Updating 6c6ed5d..b88713c
Fast-forward
 check_datastax_opscenter_cassandra_bestpractice.pl | 2 +-
 check_hadoop_jmx.pl                                | 2 +-
 lib                                                | 2 +-
 3 files changed, 3 insertions(+), 3 deletions(-)
git submodule update --init --recursive
Submodule path 'lib': checked out '452b8defbe4ea77b57a82d7c3b79babd34d21626'

#  ./check_hadoop_jmx.pl -H 10.213.162.54 -P 60030 --bean Hadoop:service=HBase,name=RegionServer,sub=Server -m compactionQueueLength
Use of uninitialized value in undef operator at lib/HariSekhonUtils.pm line 563.
OK: Hadoop:service=HBase,name=RegionServer,sub=Server: compactionQueueLength=0 | 'compactionQueueLength'=0;;;

**Comment by HariSekhon** [comment]
That's odd, it checks if the handler is defined before calling undef, can you paste the output when using triple verbose mode ```-v -v -v```?

**Comment by chaitu011** [comment]
Attached output file with the verbose output.

Thanks
Anil Kumar V

[output.docx](https://github.com/HariSekhon/nagios-plugins/files/185493/output.docx)

**Comment by chaitu011** [comment]
Any update on this ?

-- Anil Kumar V

**Comment by HariSekhon** [comment]
I can't look at this right now but will try to find some time for it at the weekend.

**Comment by chaitu011** [comment]
Did you get any time to look into this..?

Thanks
Anil Kumar V

**Comment by chaitu011** [comment]
Any update on this..?

**Comment by HariSekhon** [comment]
Apologies for the unusual slowness on this - I'm really busy on several fronts. I'll try to get back to this within the next 2 weeks.

**Comment by HariSekhon** [comment]
I've just looked at this and this doesn't occur for me - the fix should be working... if you can paste the check with ```-v -v -v``` it should give me the full output to help debug it.

**Comment by chaitu011** [comment]
Already attached verbose output on 23rd post. Attaching again if you missed it

[output.docx](https://github.com/HariSekhon/nagios-plugins/files/248261/output.docx)

**Comment by HariSekhon** [comment]
I've got a Dockerized test of this which doesn't show this problem. If you have Docker available you can reproduce the tests I've done by doing:
```make update
tests/test_hbase.sh
```
This will check everything under a controlled reproducible environment. All it requires is Docker to be installed and the DOCKER_HOST environment variable to be so that it knows where to find your docker machine.

**Comment by HariSekhon** [comment]
@chaitu011 

Did you get a chance to try the Docker test which is more reproducible?

**Comment by chaitu011** [comment]
I didnt get chance to try this on docker. Will test and update you soon.

Regards
Anil Kumar V

**Comment by HariSekhon** [comment]
@chaitu011 

Any update on testing this?

**Comment by HariSekhon** [comment]
Cannot reproduce and no feedback in a few weeks.

I'll close this for now. You can re-open / comment if you manage to run the dockerized tests and reproduce it.
